git:
  depth: false
language: elixir
elixir:
  - 1.10.2
otp_release:
  - 22.0
cache:
  directories:
    - _build
    - deps
env:
  - MIX_ENV=test
install:
  - bin/ci_setup
script:
  - bin/ci
after_script:
  - bin/coverage_ci
