# In dev, we use the same build job manifest with fake images
# Since the job manifest mounts certain secrets, they have to exist
# in order to the jobs to run, even though the fake images don't use them
apiVersion: v1
data:
  dummy_file: ZHVtbXkgdmFsdWUgaGVyZQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: kaniko-aws
  namespace: default
---
apiVersion: v1
data:
  dummy_file: ZHVtbXkgdmFsdWUgaGVyZQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: kaniko-docker
  namespace: default
