# Install the source DB used to bootstrap the review app DB
# We can check for the users table to verify the copy succeeded
apiVersion: v1
kind: Namespace
metadata:
  name: test-review-app
---
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: database-source
  namespace: test-review-app
spec:
  replicas: 1
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 256Mi
  storageType: Durable
  terminationPolicy: DoNotTerminate
  version: "10.6"
  init:
    scriptSource:
      configMap:
        name: db-init
---
apiVersion: v1
data:
  init.sql: |
    \c postgres;
    CREATE TABLE users(id SERIAL, email TEXT);
    CREATE TABLE migrations(id TEXT, applied_at TIMESTAMP);
kind: ConfigMap
metadata:
  name: db-init
  namespace: test-review-app
